version: '3'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: docuseal/docuseal:latest
    volumes:
      - app-data:/data
    environment:
      FORCE_SSL: 'false'
      DATABASE_URL: mysql2://ds_db_user:P@ssw0rd@db:3306/ds_db
    networks:
      net:

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=R00tP@ass
      - MYSQL_DATABASE=ds_db
      - MYSQL_USER=ds_db_user
      - MYSQL_PASSWORD=P@ssw0rd
    volumes:
      - db-data:/var/lib/mysql:rw
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      net:

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - db
      - app
    volumes:
      - tunnel-config:/etc/cloudflared
    command: tunnel --no-autoupdate run --token 00000000000000TOKENHERE00000000000000000000
    networks:
      net:
      
volumes:
  db-data:
    driver: local
  app-data:
    driver: local
  tunnel-config:
    driver: local
    
networks:
  net:
