version: '3'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3008:3000
    volumes:
      - app-data:/data
    environment:
      FORCE_SSL: 'false'
      DATABASE_URL: mysql2://${MYSQLUSER}:${MYSQLPASS}@db:3306/${MYSQLDATABASE}
    networks:
      net:

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASS}
    volumes:
      - db-data:/var/lib/mysql:rw
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      net:

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - db
      - app
    volumes:
      - tunnel-config:/etc/cloudflared
    command: tunnel --no-autoupdate run --token ${CFTOKEN}
    networks:
      net:
      
volumes:
  db-data:
    driver: local
  app-data:
    driver: local
  tunnel-config:
    driver: local
    
networks:
  net:
